server:
  port: 9527

spring:
  application:
    name: cloud-zuul-gateway

eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka,http://eureka7003.com:7003/eureka
  instance:
    instance-id: gateway-9527.com
    prefer-ip-address: true

zuul:
  #ignored-services: cloud-dept
  prefix: /shier
  ignored-services: "*"
  routes:
    mydept.serviceId: cloud-dept
    mydept.path: /mydept/**

info:
  app.name: shier-spring-cloud
  company.name: www.shier.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$