server: 
  port: 3344 
  
spring:
  application:
    name:  cloud-config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/shi-er/msc-config.git

# 访问地址一：http://localhost:3344/neo-config/dev
# 访问地址二：http://localhost:3344/neo-config-dev.properties